namespace VerifyPro.Models;

public class Config
{
    public string PROG_CODE { get; set; }
    public string POP_PROG_CODE { get; set; }
    public string UseOpeningMessage { get; set; }
    public string ImageWithOpeningMessage { get; set; }
    public string JigWindowTitle { get; set; }
    public string Modelname { get; set; }
    public string LogFileName { get; set; }
    public string TestTypeNunber { get; set; }
    public string DestinationTypeNunber { get; set; }
    public string SERIAL_Code { get; set; }
    public string POP_linkage { get; set; }
    public string Signal_Lamp { get; set; }
    public string Output_status { get; set; }
    public string AppeararanceInspection { get; set; }
    public string Inspection_list { get; set; }
    public string HicPcbCheck { get; set; }
    public string FanPcbCheck { get; set; }
    public string HicCheckTryBoxTest { get; set; }
    public string NouryokuTypeNunber { get; set; }
    public string TestVoltage { get; set; }
    public string TENITA_SWITCH { get; set; }
    public string SAFTY_FENCE_SWITCH { get; set; }
    public string OpeningImageFileNameCR { get; set; }
    public string OpeningImageFileNameCR_GHP { get; set; }
    public string OpeningImageFileNameHIC { get; set; }
    public string OpeningImageFileNameHIC_GHP { get; set; }
    public string OpeningImageFileNameFAN { get; set; }
    public string OpeningImageFileNameBOX { get; set; }
    public string ImageFileNameHSB { get; set; }
    public string ImageFileNameFanWave { get; set; }
    public string ImageFileName7SegInitial { get; set; }
    public string ImageFileName7SegSwitch { get; set; }
    public string SELF_CHECK_BPV { get; set; }
    public string SELF_CHECK_LED { get; set; }
    public string CHECK_UB { get; set; }
    public string AC_COMP_CHECK { get; set; }
    public string FAN_WAVE_CHECK { get; set; }
    public string FAN_WAVE_RMS_VOLTAGE_CHECK { get; set; }
    public string COMP_WAVE_CHECK { get; set; }
    public string COMP_WAVE_RMS_VOLTAGE_CHECK { get; set; }
    public string CR_18V_L { get; set; }
    public string CR_18V_H { get; set; }
    public string CR_16V_L { get; set; }
    public string CR_16V_H { get; set; }
    public string CR_15V_L { get; set; }
    public string CR_15V_H { get; set; }
    public string CR_14V_L { get; set; }
    public string CR_14V_H { get; set; }
    public string CR_12V_L { get; set; }
    public string CR_12V_H { get; set; }
    public string CR_5V_L { get; set; }
    public string CR_5V_H { get; set; }
    public string HIC_15V_L { get; set; }
    public string HIC_15V_H { get; set; }
    public string HIC_12V_L { get; set; }
    public string HIC_12V_H { get; set; }
    public string HIC_5V_L { get; set; }
    public string HIC_5V_H { get; set; }
    public string HIC_AC200V_L { get; set; }
    public string HIC_AC200V_H { get; set; }
    public string HIC_DC280V_L { get; set; }
    public string HIC_DC280V_H { get; set; }
    public string FAN_5V_L { get; set; }
    public string FAN_5V_H { get; set; }
    public string AD_DifferenceMax { get; set; }
    public string DC_DifferenceMax { get; set; }
    public string DC_Micon_DifferenceMax { get; set; }
    public string SYSTEM_STOP_TxData { get; set; }
    public string SYSTEM_REBOOT_TxData { get; set; }
    public string EEPROM_INITIAL_TxData { get; set; }
    public string CR_MICON_VERISON_TxData { get; set; }
    public string HIC_MICON_VERISON_TxData { get; set; }
    public string RC_CHECK_TxData { get; set; }
    public string RC_MICON_VERISON_TxData { get; set; }
    public string RC_CHECK_RxData { get; set; }
    public string AD_CHECK_TxData { get; set; }
    public string DI_CHECK_TxData { get; set; }
    public string CONSTANT_SPEED_COMP_ON_TxData { get; set; }
    public string CONSTANT_SPEED_COMP_OFF_TxData { get; set; }
    public string VDC_CHECK_TxData { get; set; }
    public string PARAMETER_CHECK_TxData { get; set; }
    public string NOURYOKU_0HP { get; set; }
    public string NOURYOKU_8HP { get; set; }
    public string NOURYOKU_10HP { get; set; }
    public string NOURYOKU_12HP { get; set; }
    public string NOURYOKU_14HP { get; set; }
    public string NOURYOKU_16HP { get; set; }
    public string NOURYOKU_18HP { get; set; }
    public string NOURYOKU_20HP { get; set; }
    public string READ_NOURYOKU_0HP { get; set; }
    public string READ_NOURYOKU_8HP { get; set; }
    public string READ_NOURYOKU_10HP { get; set; }
    public string READ_NOURYOKU_14HP { get; set; }
    public string READ_NOURYOKU_16HP { get; set; }
    public string READ_NOURYOKU_18HP { get; set; }
    public string READ_NOURYOKU_20HP { get; set; }
    public string READ_REIBAI { get; set; }
    public string READ_SHUUHASUU { get; set; }
    public string CR_HIC_COMMUNICATION_CHECK_TxData { get; set; }
    public string CR_FAN_COMMUNICATION_CHECK_TxData { get; set; }
    public string DC_FAN1_OFF_TxData { get; set; }
    public string DC_FAN1_Speed1_TxData { get; set; }
    public string DC_FAN1_Speed2_TxData { get; set; }
    public string DC_FAN1_Speed3_TxData { get; set; }
    public string DC_FAN1_Speed4_TxData { get; set; }
    public string DC_FAN1_Speed5_TxData { get; set; }
    public string DC_FAN1_Speed6_TxData { get; set; }
    public string DC_FAN_CHECK_TxData { get; set; }
    public string DC_FAN_Rotation_Tolerance { get; set; }
    public string DC_FAN_Minimum_rotation_speed { get; set; }
    public string _52C_ON_TxData { get; set; }
    public string _52C_OFF_TxData { get; set; }
    public string HT_ON_TxData { get; set; }
    public string HT_OFF_TxData { get; set; }
    public string HT_TEST_TxData { get; set; }
    public string COMP_TEST_MODE { get; set; }
    public string COMP_TRIP_RESET_TxData { get; set; }
    public string COMP_ON_TxData { get; set; }
    public string COMP_ON_TxData_20HP { get; set; }
    public string COMP_ON_TxData_16HP { get; set; }
    public string COMP_ON_TxData_GHP { get; set; }
    public string COMP_LOW_TxData { get; set; }
    public string COMP_LOW_TxData_GHP { get; set; }
    public string COMP_OFF_TxData { get; set; }
    public string COMP_OFF_TxData_GHP { get; set; }
    public string DC_COMP_CHECK_TxData { get; set; }
    public string DC_COMP_B_CHECK_TxData { get; set; }
    public string FAN_WAIT { get; set; }
    public string DC_COMP_WAIT { get; set; }
    public string DC_COMP_MINIMUM { get; set; }
    public string DC_COMP_HzL { get; set; }
    public string DC_COMP_HzH { get; set; }
    public string DC_COMP2_HzL { get; set; }
    public string DC_COMP2_HzH { get; set; }
    public string DI_Normal { get; set; }
    public string DI_63PH { get; set; }
    public string DI_Silent { get; set; }
    public string DI_Sonw { get; set; }
    public string DI_Test { get; set; }
    public string DI_Ap { get; set; }
    public string DI_Ub { get; set; }
    public string DI_NumComp { get; set; }
    public string DI_DRM1 { get; set; }
    public string DI_DRM2 { get; set; }
    public string DI_ForcedStop { get; set; }
    public string DI_63PH_OPEN { get; set; }
    public string DI2_Normal { get; set; }
    public string DI2_63PH { get; set; }
    public string DI2_Silent { get; set; }
    public string DI2_Sonw { get; set; }
    public string DI2_Test { get; set; }
    public string DI2_Ap { get; set; }
    public string DI2_Ub { get; set; }
    public string DI2_NumComp { get; set; }
    public string DI2_DRM1 { get; set; }
    public string DI2_DRM2 { get; set; }
    public string DI2_ForcedStop { get; set; }
    public string DI2_63PH_OPEN { get; set; }
    public string REBOOT_WaitTime { get; set; }
    public string EEPROM_INITIAL_WaitTime { get; set; }
    public string EEPROM_PARAMETERS_WaitTime { get; set; }
    public string CR_MICON_NAME { get; set; }
    public string CR_MICON_NAME_ZEB { get; set; }
    public string CR_MICON_NAME_COLD { get; set; }
    public string CR_MICON_NAME_GHP { get; set; }
    public string CR_MICON_NAME_8N { get; set; }
    public string DUMMY_CR_MICON_NAME { get; set; }
    public string RC_MICON_NAME { get; set; }
    public string CR_MICON_VERSION { get; set; }
    public string CR_MICON_VERSION_ZEB { get; set; }
    public string CR_MICON_VERSION_COLD { get; set; }
    public string CR_MICON_VERSION_GHP { get; set; }
    public string CR_MICON_VERSION_8N { get; set; }
    public string HIC_MICON_VERSION { get; set; }
    public string FAN_MICON_VERSION { get; set; }
    public string DUMMY_CR_MICON_VERSION { get; set; }
    public string DUMMY_HIC_MICON_VERSION { get; set; }
    public string DUMMY_FAN_MICON_VERSION { get; set; }
    public string LOW_TEMP_SENSOR_LOW_L { get; set; }
    public string LOW_TEMP_SENSOR_LOW_H { get; set; }
    public string LOW_TEMP_SENSOR_HIGH_L { get; set; }
    public string LOW_TEMP_SENSOR_HIGH_H { get; set; }
    public string HIGH_TEMP_SENSOR_LOW_L { get; set; }
    public string HIGH_TEMP_SENSOR_LOW_H { get; set; }
    public string HIGH_TEMP_SENSOR_HIGH_L { get; set; }
    public string HIGH_TEMP_SENSOR_HIGH_H { get; set; }
    public string PRESSURE_SENSOR_LOW_L { get; set; }
    public string PRESSURE_SENSOR_LOW_H { get; set; }
    public string PRESSURE_SENSOR_HIGH_L { get; set; }
    public string PRESSURE_SENSOR_HIGH_H { get; set; }
    public string CT_NO_LOAD_L { get; set; }
    public string CT_NO_LOAD_H { get; set; }
    public string CTL_MAX_LOAD_L { get; set; }
    public string CTL_MAX_LOAD_H { get; set; }
    public string CTL_MAX_LOAD_T_Phase_Diff { get; set; }
    public string CT_INV_LOAD_L { get; set; }
    public string CT_INV_LOAD_H { get; set; }
    public string CT_34_LOAD_L { get; set; }
    public string CT_34_LOAD_H { get; set; }
    public string CT_34_S_Phase_LOAD_L { get; set; }
    public string CT_34_S_Phase_LOAD_H { get; set; }
    public string FAN_SHUNT_LOAD_L { get; set; }
    public string FAN_SHUNT_LOAD_H { get; set; }
    public string FAN2_SHUNT_LOAD_L { get; set; }
    public string FAN2_SHUNT_LOAD_H { get; set; }
    public string FAN_WAVE_CHECK_L { get; set; }
    public string FAN_WAVE_CHECK_H { get; set; }
    public string FAN_WAVE_CHECK_DEV { get; set; }
    public string HBS_TerminationOFF_L { get; set; }
    public string HBS_TerminationON_L { get; set; }
    public string HBS_TerminationON_H { get; set; }
}